export const selectors = {
    auth: {
        emailInput: '[name="email"]',
        passwordInput: '[name="password"]',
        loginButton: '#click-login',
        toastMessage: '[data-cy="toast-message"], .Toastify__toast-body, .text-sm > :nth-child(2)',
    },
    cookies: {
        acceptAllButton: 'button:contains("Accept All")',
        declineButton: 'button:contains("Decline Non-Essential")',
        preferenceCenterButton: 'button:contains("Preference Center")',
    },
    sidebar: {
        jobsButton: 'button[onclick*="create-job"], button:has(svg), button:has(.BagIcon)',
        dashboardButton: 'button[onclick*="dashboard"]',
    },
    workspace: {
        switcher: '[data-cy="workspace-switcher"]',
        option: (name) => `[data-cy="workspace-option-${name}"]`,
    },
    jobs: {
        addJobButton: '#click-add-job',
        fixedQuestionsOption: '[data-cy="create-fixed-job"]',
        dynamicQuestionsOption: '[data-cy="create-dynamic-job"]',
        jobTitleInput: '[name="title"]',
        jobDescriptionEditor: '[data-cy="job-description-editor"], .notranslate',
        jobTypeSelect: '[data-cy="job-type-select"], [placeholder="Select Job Type"]',
        interviewDurationSelect: '[data-cy="interview-duration-select"]',
        publishQuestionsButton: '#click-publish-job-questions',
        submitFooterButton: '#submit-dynamic-interview',
        copyInterviewLinkButton: '#copy-interview-link',
        candidateInterviewLink: '[data-cy="candidate-interview-link"]',
        publishedModal: '#backdrop',
    },
    candidate: {
        nameInput: '[data-cy="candidate-name-input"], [placeholder="Name"]',
        emailInput: '[data-cy="candidate-email-input"], [placeholder="Email"]',
        countrySelect: '[data-cy="candidate-country-select"], button[role="combobox"]',
        phoneInput: '[data-cy="candidate-phone-input"], [placeholder="Phone number"]',
        termsCheckbox: '[data-cy="candidate-terms-checkbox"], [type="checkbox"]',
        proceedButton: '#proceed-interview-click-candidate',
        devicesChecked: '#devices_checked',
        joinNowButton: '#join-now-interview',
        startInterviewButton: '#start-interview-click-candidate',
    },
};
